default:
  image: gitlab.virtualcitysystems.de:5050/vcsuite/devops/gitlabrunner/node:14

variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_PROJECT_PATH_SLUG/$CI_COMMIT_REF_SLUG

stages:
  - build
  - test

.template: &job_definition
  only:
    - /^(feature-.*|hotfix-.*|master|release-.*)$/
  tags:
    - linux-2.0

build:
  <<: *job_definition
  script:
    - npm set registry 'http://npmregistry:4873'
    - npm i
  stage: build

.after_build_template: &after_build_definition
  <<: *job_definition
  variables:
    GIT_STRATEGY: none

lint:
  <<: *after_build_definition
  stage: test
  script:
    - npm run lint

# audit:
#   <<: *after_build_definition
#   stage: test
#   script:
#     - npm audit --production --audit-level=low
